# 复活需要的花费
ResurrectionCosts:
  # 复活需要的 hp
  Hp: 0
  # 是否需要在手中放置一件附魔物品作为祭品
  EnchantItemsInHand: false
  # 复活需要的资源列表
  # <item.id>: <int>
  ResourceList:
    AIR: 0

worlds:
  - "world"
  - "world_nether"
  - "world_the_end"

# 复活 cd
# ResurrectionCoolDown: -1

ResurrectSelf: "你不能尝试复活你自己!"
NotEnough: "你必须有足够的祭品"
NotEnoughDetail: "你缺少%count%个%name%"
NoEnchantItem: "你必须使用正确的附魔装备来复活玩家！"
NotEnoughHp: "你至少需要%hp%血来复活玩家！"
MustHaveTarget: "你必须指定一个玩家！"
NotExiled: "玩家未被放逐"
AlreadyExiled: "玩家尚未被放逐"
SuccessResurrect: "%player%已经被%from%成功复活"
OpOnly: "只有 op 能这么做"
SuccessExiled: "玩家%player%已经被成功放逐"
NotSafe: "目标所在方块不安全"

